config/routes.rb
LinkLoader::Application.routes.draw do

  match 'links/:id/approve' => 'links#approve'
  match 'links/:id/reject' => 'links#reject'
  match 'links/:id/feature' => 'links#feature'
  
  resources :links
  
  match 'searches/:id/update_results' => 'searches#update_results'
  match 'searches/:id/links' => 'searches#links'
  match 'searches/:id/featured_link' => 'searches#featured_link'
  match 'searches/update_all' => 'searches#update_all'
  match 'searches/:id/most_popular_link' => 'searches#most_popular_link'
  match 'searches/:id/random_link' => 'searches#random_link'
  match 'searches/:id/stream' => 'searches#stream'
  match 'searches/:id/stream_details' => 'searches#stream_details'
  
  resources :searches
  
  root :to => 'searches#index'
  

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :search
  def add_source(handle)
    list_of_sources = []
    list_of_sources = self.sources.split(",") unless self.sources == nil
    list_of_sources << "@"+handle
    self.sources = list_of_sources.join(",")
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  def feature
    @link = Link.find(params[:id])
    @search = Search.find(@link.search_id)
    @search.featured_link_id = @link.id
    @search.save
    redirect_to "/searches/"+@link.search_id.to_s+"/links"
  end
  
  def approve
    @link = Link.find(params[:id])
    @link.moderation_status = :approved
    @link.save
    redirect_to "/searches/"+@link.search_id.to_s+"/links"
  end

  def reject
    @link = Link.find(params[:id])
    @link.moderation_status = :rejected
    @link.save
    redirect_to "/searches/"+@link.search_id.to_s+"/links"
  end
  

  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for @link, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Link</legend>

    <div class="control-group">
      <%= f.label :search_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :search_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :url, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :frequency, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :frequency, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sources, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :sources, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', links_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/links/edit.html.erb
<%= render :partial => 'form' %>

app/views/links/index.html.erb
<h1>Links</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Search</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.id %></td>
        <td><%= link_to link.search_id, link_path(link) %></td>
        <td><%= link.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_link_path(link), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', link_path(link), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_link_path, :class => 'btn btn-primary' %>

app/views/links/new.html.erb
<%= render :partial => 'form' %>

app/views/links/show.html.erb
<h1>Link</h1>

<p>
  <b>Search</b><br>
  <%= @link.search_id %>
</p>

<p>
  <b>Url</b><br>
  <%= @link.url %>
</p>

<p>
  <b>Frequency</b><br>
  <%= @link.frequency %>
</p>

<p>
  <b>Sources</b><br>
  <%= @link.sources %>
</p>

<div class="form-actions">
  <%= link_to 'Back', links_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_link_path(@link), :class => 'btn' %>
  <%= link_to 'Delete', link_path(@link), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>