config/routes.rb
LinkLoader::Application.routes.draw do

  match 'links/:id/approve' => 'links#approve'
  match 'links/:id/reject' => 'links#reject'
  match 'links/:id/feature' => 'links#feature'
  
  resources :links
  
  match 'searches/:id/update_results' => 'searches#update_results'
  match 'searches/:id/links' => 'searches#links'
  match 'searches/:id/featured_link' => 'searches#featured_link'
  match 'searches/update_all' => 'searches#update_all'
  match 'searches/:id/most_popular_link' => 'searches#most_popular_link'
  match 'searches/:id/random_link' => 'searches#random_link'
  match 'searches/:id/stream' => 'searches#stream'
  match 'searches/:id/stream_details' => 'searches#stream_details'
  
  resources :searches
  
  root :to => 'searches#index'
  

end

app/models/search.rb
class Search < ActiveRecord::Base
  has_many :links
  
  def has_featured_link?
    featured_link_id!=nil && featured_link_id!=0
  end
  
  def been_run?
    self.last_id != nil && self.last_id != ""
  end

  def update_results
    new_tweets = latest_results
    found_links_count = save_tweeted_links(new_tweets)
    found_links_count
  end
  
  def self.update_all
    Rails::logger.info("Starting to update all active searches:")
    self.all.each do |s|
      if s.active?
        links_found = s.update_results
        Rails::logger.info("  Updated search results for #{s.query} - got #{links_found} reults")
      else 
        Rails::logger.info("  Skipping inactive search #{s.query}")
      end
    end
    Rails::logger.info("done updating all active searches")
  end
  
  def get_stream
    if self.category == "Search"
      results = Twitter.search(query, :rpp=>20, :include_entities=>true)
    elsif self.category == "List"
      # split query into username and listname
      query_parts = self.query.split('/')
      username = query_parts.first
      listname = query_parts.second
      results = Twitter.list_timeline(username, listname, :per_page=>100, :include_entities=>true)
    end
    return results
  end
  
  private 
    def latest_results
      results = []
      if self.category == "Search"
        results = latest_search_results 
      elsif self.category == "List"
        results = latest_list_results
      end
      # update last ID in model and only update last ID if results were received
      logger.info "Ran Twitter search for" + query
      update_attribute(:last_id, results.first.id) if results.count > 0
      # return list of tweets
      return results
    end
    
    def latest_list_results
      # split query into username and listname
      query_parts = self.query.split('/')
      username = query_parts.first
      listname = query_parts.second
      # get new results from list
      if been_run? 
        results = Twitter.list_timeline(username, listname, :per_page=>100, :since_id=>self.last_id, :include_entities=>true)
      else 
        results = Twitter.list_timeline(username, listname, :per_page=>100, :include_entities=>true)
      end
      return results
    end
    
    def latest_search_results
      # grab latest results from a search
      # if search run before, only grab new results
      if been_run? 
        results = Twitter.search(query, :since_id=>self.last_id, :rpp=>100, :include_entities=>true)
      else 
        results = Twitter.search(query, :rpp=>100, :include_entities=>true)
      end
      return results
    end
    
    def save_tweeted_links tweets
      logger.info "Trying to find links in " + tweets.count.to_s
      saved_links = 0
      tweets.each do |tweet|
        links = tweet.expanded_urls
        # this works if it's a Search
        user = tweet.from_user
        # this works if it's a List
        user = tweet.user.screen_name if user == nil
        if links != nil
          links.each do |link_url|
            cleaned_link_url = link_url.downcase
            existing_link = Link.find_by_url(cleaned_link_url)
            if existing_link == nil
              new_link = Link.new
              new_link.url = cleaned_link_url
              new_link.frequency = 1
              new_link.add_source(user)
              new_link.search_id = id
              new_link.first_tweeted = tweet.created_at
              new_link.moderation_status = :new
              new_link.save
            else
              existing_link.frequency = existing_link.frequency + 1
              existing_link.add_source(user)
              existing_link.search_id = id
              existing_link.save
            end
            saved_links = saved_links + 1
          end
        end
      end
      saved_links
    end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
 
  def update_all
    Search.update_all
    render :text => "Updated all", :status => 200
  end
 
  # show the content of the search's featured link by itself in a big iframe
  def featured_link
    # load the search item
    @search = Search.find(params[:id])
    # figure out what the featured link is
    @has_featured_link = @search.has_featured_link?
    @featured_link = Link.find(@search.featured_link_id) if @has_featured_link
    # render it without any of the standard templating
    respond_to do |format|
      format.html { render :layout => "skeletal" }
      format.json { render json: @featured_link}
    end
  end
  
   def most_popular_link
    # load the search item
    @search = Search.find(params[:id])
    # in the last 3 days
    three_days_ago=Time.now.to_i-259200
    # figure out what the most popular link is
    @popular_link = Link.where(:search_id=>@search.id).
      where("strftime('%s',first_tweeted)>'"+three_days_ago.to_s+"'").
      order("frequency DESC, first_tweeted DESC").first
    # render it without any of the standard templating
    respond_to do |format|
      format.html { render :layout => "skeletal" }
      format.json { render json: @popular_link}
    end
   end
    
   def random_link
    # load the search item
    @search = Search.find(params[:id])
    # in the last 3 days
    three_days_ago=Time.now.to_i-259200
    # figure out what the most popular link is
    @random_link = Link.where(:search_id=>@search.id).
      where("strftime('%s',first_tweeted)>'"+three_days_ago.to_s+"'").
      order("random()").first
    # render it without any of the standard templating
    respond_to do |format|
      format.html { render :layout => "skeletal" }
      format.json { render json: @random_link}
    end
  end
  
  def stream
    # load the search item
    @search = Search.find(params[:id])
    respond_to do |format|
      format.html { render :layout => "skeletal" }
    end
  end
  
   def stream_details
    # load the search item
    @search = Search.find(params[:id])
    @tweets = @search.get_stream
    respond_to do |format|
      format.html { render :layout => nil }
      format.json { render json: @tweets}
    end
  end

  def links
    @search = Search.find(params[:id])
    @recent_links = Link.where(:search_id => @search.id).order('first_tweeted DESC').limit(100)
    @featured_link = Link.find(@search.featured_link_id) if @search.has_featured_link?
  end  
  
  def update_results
    @search = Search.find(params[:id])
    @search.update_results
    redirect_to '/searches/'+@search.id.to_s+'/links'
  end
  # GET /searches
  # GET /searches.json
  
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Search</legend>

    <div class="control-group">
      <%= f.label :query, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :query, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :last_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_id, :class => 'text_field' %>
      </div>
    </div>
    
      <div class="control-group">
      <%= f.label :category, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :category, {"Search"=>"Search", "List"=>"List"} %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :featured_link_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :featured_link_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :active, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :active, :class => 'check_box' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', searches_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/searches/edit.html.erb
<%= render :partial => 'form' %>

app/views/searches/featured_link.html.erb
<h1 id="ll-feature-title"><%=@search.query%></h1>

<script type="text/javascript">
//<![CDATA[
currentContentUrl = null;

function updateContentUrl(newUrl){
	if(currentContentUrl!=newUrl){
		$('#ll-feature-content').attr('src',newUrl);
		currentContentUrl = newUrl;
	}
}

function fetchFeaturedLink(){
	$.getJSON('/searches/<%=@search.id%>/featured_link.json', function(data) {
		updateContentUrl(data.url);
	});
}

function startPeriodicUpdating(){
	fetchFeaturedLink();
	handle = setInterval("fetchFeaturedLink()", 5000); 
}

$(startPeriodicUpdating);
//]]>
</script>

<iframe id="ll-feature-content">

app/views/searches/index.html.erb
<h1>Searches</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Query</th>
      <th>Category</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.id %></td>
        <td><%= link_to search.query, search_path(search) %></td>
        <td><%= search.category %></td>
        <td><%= search.created_at %></td>
        <td>
          <%= link_to 'Update Results', '/searches/'+search.id.to_s+'/update_results', :class => 'btn btn-mini' %>
          <%= link_to 'See Links', '/searches/'+search.id.to_s+'/links', :class => 'btn btn-mini' %>
          <%= link_to 'Featured Link', '/searches/'+search.id.to_s+'/featured_link', :class => 'btn btn-mini' %>
          <%= link_to 'Most Popular Link', '/searches/'+search.id.to_s+'/most_popular_link', :class => 'btn btn-mini' %>
          <%= link_to 'Random Link', '/searches/'+search.id.to_s+'/random_link', :class => 'btn btn-mini' %>
          <%= link_to 'Stream', '/searches/'+search.id.to_s+'/stream', :class => 'btn btn-mini' %>
          <br />
          <%= link_to 'Edit', edit_search_path(search), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', search_path(search), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_search_path, :class => 'btn btn-primary' %>

app/views/searches/links.html.erb
<h1><%= @search.query %></h1>

<div class="link-list">
	<% @recent_links.each do |l| %>
		<%
		moderationCss = ""
		rowCss = ""
		case l.moderation_status
		when 'rejected'
			moderationCss = "label-important"
		when 'new'
			moderationCss = "label-info"
		when 'approved'
			moderationCss = "label-success"
		end
		%>
	
	<div class="row link-wrapper link-<%=l.moderation_status%>">
		<div class="span1">
			<% if l.id == @search.featured_link_id %>
				<span class="label label-warning">FEATURED</span>
			<% end %>
			<span class="label <%=moderationCss%>"><%=l.moderation_status %></span>
		</div>
		<div class="span7">
			<%=link_to(l.url,l.url) %>
			<br />
			<small><%= time_ago_in_words(l.first_tweeted) %>: <%=l.sources.split(",").join(", ")%></small>
		</div>
		<div class="span1"><%=l.frequency %></div>
		<div class="span3"> 
			<a class="btn" href="/links/<%=l.id%>/approve">Approve</a>  
			<a class="btn" href="/links/<%=l.id%>/reject">Reject</a>  
			<a class="btn" href="/links/<%=l.id%>/feature">Feature</a> 
		</div>
	</div>
	<% end %>
</div>

app/views/searches/most_popular_link.html.erb
<h1 id="ll-feature-title"><%=@search.query%></h1>

<script type="text/javascript">
//<![CDATA[
currentContentUrl = null;

function updateContentUrl(newUrl){
	if(currentContentUrl!=newUrl){
		$('#ll-feature-content').attr('src',newUrl);
		currentContentUrl = newUrl;
	}
}

function fetchPopularLink(){
	$.getJSON('/searches/<%=@search.id%>/most_popular_link.json', function(data) {
		updateContentUrl(data.url);
	});
}

function startPeriodicUpdating(){
	fetchPopularLink();
	handle = setInterval("fetchPopularLink()", 5000); 
}

$(startPeriodicUpdating);
//]]>
</script>

<iframe id="ll-feature-content">

app/views/searches/new.html.erb
<%= render :partial => 'form' %>

app/views/searches/random_link.html.erb
<h1 id="ll-feature-title"><%=@search.query%></h1>

<script type="text/javascript">
//<![CDATA[
// the URL the iframe is currently showing
currentContentUrl = null;

// if it's a new URL, change what the iframe is showing
function updateContentUrl(newUrl){
	if(currentContentUrl!=newUrl){
		$('#ll-feature-content').attr('src',newUrl);
		currentContentUrl = newUrl;
	}
}
// asks server for most popular link in json format
function fetchLink(){
	$.getJSON('/searches/<%=@search.id%>/random_link.json', function(data) {
		updateContentUrl(data.url);
	});
}

// get popular link and start checking for new one every x seconds
function startPeriodicUpdating(){
	fetchLink();
	handle = setInterval("fetchLink()", 50000); 
}
// start when webpage loads
$(startPeriodicUpdating);
//]]>
</script>
<!-- iframe content here -->
<iframe id="ll-feature-content">

app/views/searches/show.html.erb
<h1>Search</h1>

<p>
  <b>Query</b><br>
  <%= @search.query %>
</p>

<p>
  <b>Category</b><br>
  <%= @search.category %>
</p>

<p>
  <b>Last Id</b><br>
  <%= @search.last_id %>
</p>

<p>
  <b>Active</b><br>
  <%= @search.active?.to_s %>
</p>

<p>
  <b>Featured Link Id</b><br>
  <%= @search.featured_link_id %>
</p>

<div class="form-actions">
  <%= link_to 'Back', searches_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_search_path(@search), :class => 'btn' %>
  <%= link_to 'Delete', search_path(@search), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/searches/stream.html.erb
<h1 id="ll-feature-title"><%=@search.query%></h1>

<script type="text/javascript">
//<![CDATA[

// if it's a new URL, change what the iframe is showing
function updateStream(newUrl){
		$('#ll-feature-content').attr('src',"/searches/<%=@search.id%>/stream_details");
}


// get popular link and start checking for new one every x seconds
function startPeriodicUpdating(){
	updateStream();
	handle = setInterval("updateStream()", 50000); 
}
// start when webpage loads
$(startPeriodicUpdating);
//]]>
</script>
<!-- iframe content here -->
<iframe id="ll-feature-content">

app/views/searches/stream_details.html.erb
<div>
	<% @tweets.each do |t| %>
		<%=t.user.screen_name%>
		<%=t.user.profile_image_url%>
		<%=t.text%>
	<% end %>
</div>